config/routes.rb
Rails.application.routes.draw do
  resources :disposisi
  get 'aktivitas/index'
  
  resources :aktivitas

  resources :derajat_pengaman
  resources :sifat_surat_masuk
  resources :status_surat_masuk
  resources :status_akun
  get 'signup', to: 'pengguna#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :seksi
  resources :jabatan
  resources :status_kepegawaian
  resources :pengguna
  resources :daftar_pustaka do
    resources :komentar
  end
  resources :surat_masuk
  
  resources :surat_keluar do
    resources :komentar
  end

  resources :komentar do
    resources :komentar
  end
  
  get 'dasbor/index'

  get 'salam/index'
  
  root 'salam#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daftar_pustaka.rb
class DaftarPustaka < ApplicationRecord
  has_attached_file :lampiran
  has_many :komentar, as: :commentable
  validates :judul, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Surat Ijin" }
  validates :keterangan, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Untuk pengajuan ijin, maksimal satu hari setelah tidak masuk" }
  validates_attachment :lampiran
  do_not_validate_attachment_file_type :lampiran
end

app/models/derajat_pengaman.rb
class DerajatPengaman < ApplicationRecord
  has_and_belongs_to_many :surat_masuk
end

app/models/disposisi.rb
class Disposisi < ApplicationRecord
end

app/models/jabatan.rb
class Jabatan < ApplicationRecord
  validates :nama, presence: true, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter - contoh: Kepala" }
  has_and_belongs_to_many :pengguna
end

app/models/komentar.rb
class Komentar < ApplicationRecord
  has_attached_file :lampiran
  belongs_to :commentable, polymorphic: true
  has_many :komentar, as: :commentable
  validates :isi, presence: true, length: { minimum: 2, message: "harus terdiri dari minimal 2 karakter - contoh: Ok" }
  validates_attachment :lampiran
  do_not_validate_attachment_file_type :lampiran
end

app/models/pengguna.rb
class Pengguna < ApplicationRecord
  has_secure_password
  validates :nama, presence: true, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter - contoh: Rifaid" }
  
  validates :password, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter" }
  
  has_and_belongs_to_many :status_kepegawaian
  has_and_belongs_to_many :jabatan
  has_and_belongs_to_many :seksi
  has_and_belongs_to_many :status_akun
  has_and_belongs_to_many :surat_keluar
  
  validates_uniqueness_of :nama
  has_many :komentar
end

app/models/seksi.rb
class Seksi < ApplicationRecord
  validates :nama, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Tata Usaha" }
  has_and_belongs_to_many :pengguna
  has_and_belongs_to_many :surat_keluar
end

app/models/sifat_surat_masuk.rb
class SifatSuratMasuk < ApplicationRecord
  has_and_belongs_to_many :surat_masuk
end

app/models/status_akun.rb
class StatusAkun < ApplicationRecord
  attribute :keterangan, :string, default: "Tidak aktif"
  validates :keterangan, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter - contoh: Aktif" }
  has_and_belongs_to_many :pengguna
end

app/models/status_kepegawaian.rb
class StatusKepegawaian < ApplicationRecord
  validates :status_kepegawaian, presence: true, length: { minimum: 3, message: "harus terdiri dari minimal 3 karakter - contoh: PTT" }
  has_and_belongs_to_many :pengguna
end

app/models/surat_keluar.rb
class SuratKeluar < ApplicationRecord
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.current_user }
  
  has_attached_file :lampiran_dokumen
  has_many :komentar, as: :commentable
  validates :judul, presence: true, length: { minimum: 8, message: "harus terdiri dari minimal 8 karakter - contoh: Undangan" }
  validates :keterangan, presence: true, length: { minimum: 8, message: "harus terdiri dari minimal 8 karakter - contoh: Untuk kegiatan HAB pada tanggal 3 Januari berlokasi di Aula Kantor Kementerian Agama Sumba Tengah" }
  validates_attachment :lampiran_dokumen
  do_not_validate_attachment_file_type :lampiran_dokumen
  has_and_belongs_to_many :pengguna
  has_and_belongs_to_many :seksi
end

app/models/surat_masuk.rb
class SuratMasuk < ApplicationRecord
  validates :nomor_surat, presence: true, format: { with: /[\/\.A-Za-z0-9]/,
    message: "hanya diperkenankan terdiri dari rangkaian huruf dan angka serta karakter / (garis miring) dan . (titik)" }
  validates :dari, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter"  }
  validates :perihal, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter"  }
  has_and_belongs_to_many :status_surat_masuk
  has_and_belongs_to_many :sifat_surat_masuk
  has_and_belongs_to_many :derajat_pengaman
end

app/controllers/derajat_pengaman_controller.rb
class DerajatPengamanController < ApplicationController
  before_action :set_derajat_pengaman, only: [:show, :edit, :update, :destroy]

  # GET /derajat_pengaman
  # GET /derajat_pengaman.json
  def index
    @derajat_pengaman = DerajatPengaman.all
  end

  # GET /derajat_pengaman/1
  # GET /derajat_pengaman/1.json
  def show
  end

  # GET /derajat_pengaman/new
  def new
    @derajat_pengaman = DerajatPengaman.new
  end

  # GET /derajat_pengaman/1/edit
  def edit
  end

  # POST /derajat_pengaman
  # POST /derajat_pengaman.json
  def create
    @derajat_pengaman = DerajatPengaman.new(derajat_pengaman_params)

    respond_to do |format|
      if @derajat_pengaman.save
        format.html { redirect_to @derajat_pengaman, notice: 'Derajat pengaman was successfully created.' }
        format.json { render :show, status: :created, location: @derajat_pengaman }
      else
        format.html { render :new }
        format.json { render json: @derajat_pengaman.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /derajat_pengaman/1
  # PATCH/PUT /derajat_pengaman/1.json
  def update
    respond_to do |format|
      if @derajat_pengaman.update(derajat_pengaman_params)
        format.html { redirect_to @derajat_pengaman, notice: 'Derajat pengaman was successfully updated.' }
        format.json { render :show, status: :ok, location: @derajat_pengaman }
      else
        format.html { render :edit }
        format.json { render json: @derajat_pengaman.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /derajat_pengaman/1
  # DELETE /derajat_pengaman/1.json
  def destroy
    @derajat_pengaman.destroy
    respond_to do |format|
      format.html { redirect_to derajat_pengaman_index_url, notice: 'Derajat pengaman was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_derajat_pengaman
      @derajat_pengaman = DerajatPengaman.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def derajat_pengaman_params
      params.require(:derajat_pengaman).permit(:nama)
    end
end

app/helpers/aktivitas_helper.rb
module AktivitasHelper
end

app/helpers/dasbor_helper.rb
module DasborHelper
end

app/helpers/derajat_pengaman_helper.rb
module DerajatPengamanHelper
end

app/helpers/disposisi_helper.rb
module DisposisiHelper
end

app/helpers/jabatan_helper.rb
module JabatanHelper
end

app/helpers/pengguna_helper.rb
module PenggunaHelper
end

app/helpers/salam_helper.rb
module SalamHelper
end

app/helpers/seksi_helper.rb
module SeksiHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/derajat_pengaman/_form.html.haml
= simple_form_for(@derajat_pengaman, html: { class: 'form-horizontal add-left-margin' }, defaults: { wrapper_html: { class: 'col-md-4 mb-2' } } ) do |f|
  - if @derajat_pengaman.errors.any?
    #error_explanation
      %h2= "#{pluralize(@derajat_pengaman.errors.count, "error")} menyebabkan Derajat Pengaman yang dibuat tidak dapat disimpan:"
      %ul
        - @derajat_pengaman.errors.full_messages.each do |message|
          %li= message
  .row
    = f.input :nama, label_method: :nama
  .row
    = button_tag(type: 'submit', class: "btn btn-primary") do
      %i.fa.d-inline.fa-lg.fa-save
      Simpan

app/views/derajat_pengaman/edit.html.haml
= render 'elements/header'
%h1 Edit Derajat Pengaman

= render 'form'

.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-close" title="Batal edit derajat pengaman"></i></button>'.html_safe, derajat_pengaman_index_path, class: 'center-block'
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-expand" title="Tampilkan derajat pengaman"></i></button>'.html_safe, @derajat_pengaman, class: 'center-block add-left-margin'

app/views/derajat_pengaman/index.html.haml
= render 'elements/header'
%h1 Daftar Derajat Pengaman

.py-5
  .row
    .col-md-12
      %table.table
        %thead
          %tr
            %th Derajat Pengaman
            %th
            %th
            %th
        
        %tbody
          - @derajat_pengaman.each do |derajat_pengaman|
            %tr
              %td= derajat_pengaman.nama
              %td= link_to '<i class="fa d-inline fa-lg fa-expand" title="Tampilkan derajat pengaman"></i>'.html_safe, derajat_pengaman, class: 'btn btn-sm btn-primary mx-1'
              %td= link_to '<i class="fa d-inline fa-lg fa-pencil" title="Edit derajat pengaman"></i>'.html_safe, edit_derajat_pengaman_path(derajat_pengaman), class: 'btn btn-sm btn-primary mx-1'
              %td= link_to '<i class="fa d-inline fa-lg fa-trash" title="Hapus derajat pengaman"></i>'.html_safe, derajat_pengaman, method: :delete, data: { confirm: 'Anda yakin ingin menghapus derajat pengaman ini?' }, class: 'btn btn-sm btn-primary mx-1'

.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Kembali ke Dasbor"></i></button>'.html_safe, dasbor_index_path, class: 'center-block'
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-plus" title="Buat status surat masuk"></i></button>'.html_safe, new_derajat_pengaman_path, class: 'center-block add-left-margin'

app/views/derajat_pengaman/new.html.haml
= render 'elements/header'
.container
%h1.add-left-margin Membuat Derajat Pengaman

= render 'form'

%br
.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Batal membuat derajat pengaman"></i></button>'.html_safe, derajat_pengaman_index_path, class: 'center-block'

app/views/derajat_pengaman/show.html.haml
= render 'elements/header'
%p#notice= notice
.add-trbl-margin
  %p
    %b Derajat pengaman:
    = @derajat_pengaman.nama

  = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-pencil" title="Edit derajat pengaman"></i></button>'.html_safe, edit_derajat_pengaman_path(@derajat_pengaman), class: 'center-block'
  .row.align-items-center.justify-content-center
    .row
      = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Kembali ke daftar derajat pengaman"></i></button>'.html_safe, derajat_pengaman_index_path, class: 'center-block'


%p#notice= notice

%p
  %b Nama:
  = @derajat_pengaman.nama

= link_to 'Edit', edit_derajat_pengaman_path(@derajat_pengaman)
\|
= link_to 'Back', derajat_pengaman_index_path