config/routes.rb
Rails.application.routes.draw do
  resources :disposisi
  get 'aktivitas/index'
  
  resources :aktivitas

  resources :derajat_pengaman
  resources :sifat_surat_masuk
  resources :status_surat_masuk
  resources :status_akun
  get 'signup', to: 'pengguna#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :seksi
  resources :jabatan
  resources :status_kepegawaian
  resources :pengguna
  resources :daftar_pustaka do
    resources :komentar
  end
  resources :surat_masuk
  
  resources :surat_keluar do
    resources :komentar
  end

  resources :komentar do
    resources :komentar
  end
  
  get 'dasbor/index'

  get 'salam/index'
  
  root 'salam#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daftar_pustaka.rb
class DaftarPustaka < ApplicationRecord
  has_attached_file :lampiran
  has_many :komentar, as: :commentable
  validates :judul, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Surat Ijin" }
  validates :keterangan, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Untuk pengajuan ijin, maksimal satu hari setelah tidak masuk" }
  validates_attachment :lampiran
  do_not_validate_attachment_file_type :lampiran
end

app/models/derajat_pengaman.rb
class DerajatPengaman < ApplicationRecord
  has_and_belongs_to_many :surat_masuk
end

app/models/disposisi.rb
class Disposisi < ApplicationRecord
end

app/models/jabatan.rb
class Jabatan < ApplicationRecord
  validates :nama, presence: true, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter - contoh: Kepala" }
  has_and_belongs_to_many :pengguna
end

app/models/komentar.rb
class Komentar < ApplicationRecord
  has_attached_file :lampiran
  belongs_to :commentable, polymorphic: true
  has_many :komentar, as: :commentable
  validates :isi, presence: true, length: { minimum: 2, message: "harus terdiri dari minimal 2 karakter - contoh: Ok" }
  validates_attachment :lampiran
  do_not_validate_attachment_file_type :lampiran
end

app/models/pengguna.rb
class Pengguna < ApplicationRecord
  has_secure_password
  validates :nama, presence: true, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter - contoh: Rifaid" }
  
  validates :password, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter" }
  
  has_and_belongs_to_many :status_kepegawaian
  has_and_belongs_to_many :jabatan
  has_and_belongs_to_many :seksi
  has_and_belongs_to_many :status_akun
  has_and_belongs_to_many :surat_keluar
  
  validates_uniqueness_of :nama
  has_many :komentar
end

app/models/seksi.rb
class Seksi < ApplicationRecord
  validates :nama, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Tata Usaha" }
  has_and_belongs_to_many :pengguna
  has_and_belongs_to_many :surat_keluar
end

app/models/sifat_surat_masuk.rb
class SifatSuratMasuk < ApplicationRecord
  has_and_belongs_to_many :surat_masuk
end

app/models/status_akun.rb
class StatusAkun < ApplicationRecord
  attribute :keterangan, :string, default: "Tidak aktif"
  validates :keterangan, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter - contoh: Aktif" }
  has_and_belongs_to_many :pengguna
end

app/models/status_kepegawaian.rb
class StatusKepegawaian < ApplicationRecord
  validates :status_kepegawaian, presence: true, length: { minimum: 3, message: "harus terdiri dari minimal 3 karakter - contoh: PTT" }
  has_and_belongs_to_many :pengguna
end

app/models/surat_keluar.rb
class SuratKeluar < ApplicationRecord
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.current_user }
  
  has_attached_file :lampiran_dokumen
  has_many :komentar, as: :commentable
  validates :judul, presence: true, length: { minimum: 8, message: "harus terdiri dari minimal 8 karakter - contoh: Undangan" }
  validates :keterangan, presence: true, length: { minimum: 8, message: "harus terdiri dari minimal 8 karakter - contoh: Untuk kegiatan HAB pada tanggal 3 Januari berlokasi di Aula Kantor Kementerian Agama Sumba Tengah" }
  validates_attachment :lampiran_dokumen
  do_not_validate_attachment_file_type :lampiran_dokumen
  has_and_belongs_to_many :pengguna
  has_and_belongs_to_many :seksi
end

app/models/surat_masuk.rb
class SuratMasuk < ApplicationRecord
  validates :nomor_surat, presence: true, format: { with: /[\/\.A-Za-z0-9]/,
    message: "hanya diperkenankan terdiri dari rangkaian huruf dan angka serta karakter / (garis miring) dan . (titik)" }
  validates :dari, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter"  }
  validates :perihal, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter"  }
  has_and_belongs_to_many :status_surat_masuk
  has_and_belongs_to_many :sifat_surat_masuk
  has_and_belongs_to_many :derajat_pengaman
end

app/controllers/daftar_pustaka_controller.rb
class DaftarPustakaController < ApplicationController
  before_action :authorize
  before_action :set_daftar_pustaka, only: [:show, :edit, :update, :destroy]

  # GET /daftar_pustaka
  # GET /daftar_pustaka.json
  def index
    @daftar_pustaka = DaftarPustaka.all
  end

  # GET /daftar_pustaka/1
  # GET /daftar_pustaka/1.json
  def show
  end

  # GET /daftar_pustaka/new
  def new
    @daftar_pustaka = DaftarPustaka.new
  end

  # GET /daftar_pustaka/1/edit
  def edit
  end

  # POST /daftar_pustaka
  # POST /daftar_pustaka.json
  def create
    @daftar_pustaka = DaftarPustaka.new(daftar_pustaka_params)

    respond_to do |format|
      if @daftar_pustaka.save
        format.html { redirect_to @daftar_pustaka, notice: 'Daftar pustaka was successfully created.' }
        format.json { render :show, status: :created, location: @daftar_pustaka }
      else
        format.html { render :new }
        format.json { render json: @daftar_pustaka.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daftar_pustaka/1
  # PATCH/PUT /daftar_pustaka/1.json
  def update
    respond_to do |format|
      if @daftar_pustaka.update(daftar_pustaka_params)
        format.html { redirect_to @daftar_pustaka, notice: 'Daftar pustaka was successfully updated.' }
        format.json { render :show, status: :ok, location: @daftar_pustaka }
      else
        format.html { render :edit }
        format.json { render json: @daftar_pustaka.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daftar_pustaka/1
  # DELETE /daftar_pustaka/1.json
  def destroy
    @daftar_pustaka.destroy
    respond_to do |format|
      format.html { redirect_to daftar_pustaka_index_url, notice: 'Daftar pustaka was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daftar_pustaka
      @daftar_pustaka = DaftarPustaka.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daftar_pustaka_params
      params.require(:daftar_pustaka).permit(:judul, :keterangan, :lampiran)
    end
end

app/helpers/aktivitas_helper.rb
module AktivitasHelper
end

app/helpers/daftar_pustaka_helper.rb
module DaftarPustakaHelper
end

app/helpers/dasbor_helper.rb
module DasborHelper
end

app/helpers/disposisi_helper.rb
module DisposisiHelper
end

app/helpers/jabatan_helper.rb
module JabatanHelper
end

app/helpers/pengguna_helper.rb
module PenggunaHelper
end

app/helpers/salam_helper.rb
module SalamHelper
end

app/helpers/seksi_helper.rb
module SeksiHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/daftar_pustaka/_form.html.haml
= simple_form_for(@daftar_pustaka, html: { class: 'form-horizontal add-left-margin' }, defaults: { wrapper_html: { class: 'col-md-4 mb-2' } } ) do |f|
  - if @daftar_pustaka.errors.any?
    #error_explanation
      %h2= "#{pluralize(@daftar_pustaka.errors.count, "error")} menyebabkan Daftar Pustaka yang dibuat tidak dapat disimpan:"
      %ul
        - @daftar_pustaka.errors.full_messages.each do |message|
          %li= message
  .row
    = f.input :judul, label: 'Judul'
  .row
    = f.input :keterangan, label: 'Keterangan'
  .row
    = f.input :lampiran
  .row
    = button_tag(type: 'submit', class: "btn btn-primary") do
      %i.fa.d-inline.fa-lg.fa-save
      Simpan

app/views/daftar_pustaka/edit.html.haml
= render 'elements/header'
%h1 Edit Pustaka

= render 'form'

.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-close" title="Batal edit pustaka"></i></button>'.html_safe, daftar_pustaka_index_path, class: 'center-block'
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-expand" title="Tampilkan pustaka"></i></button>'.html_safe, @daftar_pustaka, class: 'center-block add-left-margin'

app/views/daftar_pustaka/index.html.haml
= render 'elements/header'
%h1 Daftar Pustaka

.py-5
  .row
    .col-sm-12
      %table.table.table-striped
        %thead
          %tr.row
            %th.col-sm-4 Judul
            %th.col-sm-4 Keterangan
            %th.col-sm-4 Tindakan

        %tbody
          - @daftar_pustaka.each do |daftar_pustaka|
            %tr.row
              %td.col-sm-4= daftar_pustaka.judul
              %td.col-sm-4= daftar_pustaka.keterangan
              %td.col-sm-1= link_to '<i class="fa d-inline fa-lg fa-expand" title="Tampilkan pustaka"></i>'.html_safe, daftar_pustaka, class: 'btn btn-sm btn-primary mx-1'
              %td.col-sm-1= link_to '<i class="fa d-inline fa-lg fa-pencil" title="Edit pustaka"></i>'.html_safe, edit_daftar_pustaka_path(daftar_pustaka), class: 'btn btn-sm btn-primary mx-1'
              %td.col-sm-1= link_to '<i class="fa d-inline fa-lg fa-trash" title="Hapus pustaka"></i>'.html_safe, daftar_pustaka, method: :delete, data: { confirm: 'Anda yakin ingin menghapus surat ini?' }, class: 'btn btn-sm btn-primary mx-1'

.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Kembali ke Dasbor"></i></button>'.html_safe, dasbor_index_path, class: 'center-block'
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-plus" title="Buat surat keluar"></i></button>'.html_safe, new_daftar_pustaka_path, class: 'center-block add-left-margin'

app/views/daftar_pustaka/new.html.haml
= render 'elements/header'
.container
%h1.add-left-margin Membuat Pustaka

= render 'form'

%br
.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Batal membuat surat keluar"></i></button>'.html_safe, daftar_pustaka_index_path, class: 'center-block'

app/views/daftar_pustaka/show.html.haml
= render 'elements/header'
%p#notice= notice
.add-trbl-margin
  %p
    %b Judul:
    = @daftar_pustaka.judul
  %p
    %b Keterangan:
    = @daftar_pustaka.keterangan
  %p
    %b Lampiran:
    = link_to '<button class="btn btn-primary btn-circle btn-m"><i class="fa fa-lg fa-cloud-download" title="Unduh lampiran"></i></button>'.html_safe, @daftar_pustaka.lampiran.url, class: 'center-block'
  
  %br
  = simple_form_for [@daftar_pustaka, Komentar.new] do |f|
    = f.input :isi, placeholder: "Tambahkan komentar", label: false
    = f.input :lampiran, label: false
    = button_tag(type: 'submit', class: "btn btn-primary") do
      %i.fa.d-inline.fa-lg.fa-comment
      Tambah komentar
    %br
  %ul
    = render(partial: 'komentar/komentar', collection: @daftar_pustaka.komentar)
  
  = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-pencil" title="Edit pustaka"></i></button>'.html_safe, edit_daftar_pustaka_path(@daftar_pustaka), class: 'center-block'
  .row.align-items-center.justify-content-center
    .row
      = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Kembali ke daftar pustaka"></i></button>'.html_safe, daftar_pustaka_index_path, class: 'center-block'