config/routes.rb
Rails.application.routes.draw do
  resources :disposisi
  get 'aktivitas/index'
  
  resources :aktivitas

  resources :derajat_pengaman
  resources :sifat_surat_masuk
  resources :status_surat_masuk
  resources :status_akun
  get 'signup', to: 'pengguna#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions
  resources :seksi
  resources :jabatan
  resources :status_kepegawaian
  resources :pengguna
  resources :daftar_pustaka do
    resources :komentar
  end
  resources :surat_masuk
  
  resources :surat_keluar do
    resources :komentar
  end

  resources :komentar do
    resources :komentar
  end
  
  get 'dasbor/index'

  get 'salam/index'
  
  root 'salam#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daftar_pustaka.rb
class DaftarPustaka < ApplicationRecord
  has_attached_file :lampiran
  has_many :komentar, as: :commentable
  validates :judul, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Surat Ijin" }
  validates :keterangan, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Untuk pengajuan ijin, maksimal satu hari setelah tidak masuk" }
  validates_attachment :lampiran
  do_not_validate_attachment_file_type :lampiran
end

app/models/derajat_pengaman.rb
class DerajatPengaman < ApplicationRecord
  has_and_belongs_to_many :surat_masuk
end

app/models/disposisi.rb
class Disposisi < ApplicationRecord
end

app/models/jabatan.rb
class Jabatan < ApplicationRecord
  validates :nama, presence: true, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter - contoh: Kepala" }
  has_and_belongs_to_many :pengguna
end

app/models/komentar.rb
class Komentar < ApplicationRecord
  has_attached_file :lampiran
  belongs_to :commentable, polymorphic: true
  has_many :komentar, as: :commentable
  validates :isi, presence: true, length: { minimum: 2, message: "harus terdiri dari minimal 2 karakter - contoh: Ok" }
  validates_attachment :lampiran
  do_not_validate_attachment_file_type :lampiran
end

app/models/pengguna.rb
class Pengguna < ApplicationRecord
  has_secure_password
  validates :nama, presence: true, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter - contoh: Rifaid" }
  
  validates :password, length: { minimum: 6, message: "harus terdiri dari minimal 6 karakter" }
  
  has_and_belongs_to_many :status_kepegawaian
  has_and_belongs_to_many :jabatan
  has_and_belongs_to_many :seksi
  has_and_belongs_to_many :status_akun
  has_and_belongs_to_many :surat_keluar
  
  validates_uniqueness_of :nama
  has_many :komentar
end

app/models/seksi.rb
class Seksi < ApplicationRecord
  validates :nama, presence: true, length: { minimum: 10, message: "harus terdiri dari minimal 10 karakter - contoh: Tata Usaha" }
  has_and_belongs_to_many :pengguna
  has_and_belongs_to_many :surat_keluar
end

app/models/sifat_surat_masuk.rb
class SifatSuratMasuk < ApplicationRecord
  has_and_belongs_to_many :surat_masuk
end

app/models/status_akun.rb
class StatusAkun < ApplicationRecord
  attribute :keterangan, :string, default: "Tidak aktif"
  validates :keterangan, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter - contoh: Aktif" }
  has_and_belongs_to_many :pengguna
end

app/models/status_kepegawaian.rb
class StatusKepegawaian < ApplicationRecord
  validates :status_kepegawaian, presence: true, length: { minimum: 3, message: "harus terdiri dari minimal 3 karakter - contoh: PTT" }
  has_and_belongs_to_many :pengguna
end

app/models/surat_keluar.rb
class SuratKeluar < ApplicationRecord
  include PublicActivity::Model
  tracked owner: ->(controller, model) { controller.current_user }
  
  has_attached_file :lampiran_dokumen
  has_many :komentar, as: :commentable
  validates :judul, presence: true, length: { minimum: 8, message: "harus terdiri dari minimal 8 karakter - contoh: Undangan" }
  validates :keterangan, presence: true, length: { minimum: 8, message: "harus terdiri dari minimal 8 karakter - contoh: Untuk kegiatan HAB pada tanggal 3 Januari berlokasi di Aula Kantor Kementerian Agama Sumba Tengah" }
  validates_attachment :lampiran_dokumen
  do_not_validate_attachment_file_type :lampiran_dokumen
  has_and_belongs_to_many :pengguna
  has_and_belongs_to_many :seksi
end

app/models/surat_masuk.rb
class SuratMasuk < ApplicationRecord
  validates :nomor_surat, presence: true, format: { with: /[\/\.A-Za-z0-9]/,
    message: "hanya diperkenankan terdiri dari rangkaian huruf dan angka serta karakter / (garis miring) dan . (titik)" }
  validates :dari, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter"  }
  validates :perihal, presence: true, length: { minimum: 5, message: "harus terdiri dari minimal 5 karakter"  }
  has_and_belongs_to_many :status_surat_masuk
  has_and_belongs_to_many :sifat_surat_masuk
  has_and_belongs_to_many :derajat_pengaman
end

app/controllers/status_akun_controller.rb
class StatusAkunController < ApplicationController
  before_action :authorize
  before_action :set_status_akun, only: [:show, :edit, :update, :destroy]

  # GET /status_akun
  # GET /status_akun.json
  def index
    @status_akun = StatusAkun.all
  end

  # GET /status_akun/1
  # GET /status_akun/1.json
  def show
  end

  # GET /status_akun/new
  def new
    @status_akun = StatusAkun.new
  end

  # GET /status_akun/1/edit
  def edit
  end

  # POST /status_akun
  # POST /status_akun.json
  def create
    @status_akun = StatusAkun.new(status_akun_params)

    respond_to do |format|
      if @status_akun.save
        format.html { redirect_to @status_akun, notice: 'Status akun was successfully created.' }
        format.json { render :show, status: :created, location: @status_akun }
      else
        format.html { render :new }
        format.json { render json: @status_akun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_akun/1
  # PATCH/PUT /status_akun/1.json
  def update
    respond_to do |format|
      if @status_akun.update(status_akun_params)
        format.html { redirect_to @status_akun, notice: 'Status akun was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_akun }
      else
        format.html { render :edit }
        format.json { render json: @status_akun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_akun/1
  # DELETE /status_akun/1.json
  def destroy
    @status_akun.destroy
    respond_to do |format|
      format.html { redirect_to status_akun_index_url, notice: 'Status akun was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_akun
      @status_akun = StatusAkun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_akun_params
      params.require(:status_akun).permit(:keterangan)
    end
end

app/helpers/aktivitas_helper.rb
module AktivitasHelper
end

app/helpers/dasbor_helper.rb
module DasborHelper
end

app/helpers/disposisi_helper.rb
module DisposisiHelper
end

app/helpers/jabatan_helper.rb
module JabatanHelper
end

app/helpers/pengguna_helper.rb
module PenggunaHelper
end

app/helpers/salam_helper.rb
module SalamHelper
end

app/helpers/seksi_helper.rb
module SeksiHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/status_akun_helper.rb
module StatusAkunHelper
end

app/views/status_akun/_form.html.haml
= simple_form_for(@status_akun, html: { class: 'form-horizontal add-left-margin' }, defaults: { wrapper_html: { class: 'col-md-4 mb-2' } } ) do |f|
  - if @status_akun.errors.any?
    #error_explanation
      %h2= "#{pluralize(@status_akun.errors.count, "error")} menyebabkan Status Akun yang dibuat tidak dapat disimpan:"
      %ul
        - @status_akun.errors.full_messages.each do |message|
          %li= message
  .row
    = f.input :keterangan, label_method: :keterangan
  .row
    = button_tag(type: 'submit', class: "btn btn-primary") do
      %i.fa.d-inline.fa-lg.fa-save
      Simpan

app/views/status_akun/edit.html.haml
= render 'elements/header'
%h1 Edit Status Akun

= render 'form'

.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-close" title="Batal edit status akun"></i></button>'.html_safe, status_akun_index_path, class: 'center-block'
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-expand" title="Tampilkan status akun"></i></button>'.html_safe, @status_akun, class: 'center-block add-left-margin'

app/views/status_akun/index.html.haml
= render 'elements/header'
%h1 Daftar Status Akun

.py-5
  .row
    .col-md-12
      %table.table
        %thead
          %tr
            %th Status Akun
            %th
            %th
            %th
        
        %tbody
          - @status_akun.each do |status_akun|
            %tr
              %td= status_akun.keterangan
              %td= link_to '<i class="fa d-inline fa-lg fa-expand" title="Tampilkan status akun"></i>'.html_safe, status_akun, class: 'btn btn-sm btn-primary mx-1'
              %td= link_to '<i class="fa d-inline fa-lg fa-pencil" title="Edit status akun"></i>'.html_safe, edit_status_akun_path(status_akun), class: 'btn btn-sm btn-primary mx-1'
              %td= link_to '<i class="fa d-inline fa-lg fa-trash" title="Hapus status akun"></i>'.html_safe, status_akun, method: :delete, data: { confirm: 'Anda yakin ingin menghapus status akun ini?' }, class: 'btn btn-sm btn-primary mx-1'

.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Kembali ke Dasbor"></i></button>'.html_safe, dasbor_index_path, class: 'center-block'
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-plus" title="Buat status akun"></i></button>'.html_safe, new_status_akun_path, class: 'center-block add-left-margin'

app/views/status_akun/new.html.haml
= render 'elements/header'
.container
%h1.add-left-margin Membuat Status Akun

= render 'form'

%br
.row.align-items-center.justify-content-center
  .row
    = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Batal membuat status akun"></i></button>'.html_safe, status_akun_index_path, class: 'center-block'

app/views/status_akun/show.html.haml
= render 'elements/header'
%p#notice= notice
.add-trbl-margin
  %p
    %b Status akun:
    = @status_akun.keterangan

  = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-pencil" title="Edit status akun"></i></button>'.html_safe, edit_status_akun_path(@status_akun), class: 'center-block'
  .row.align-items-center.justify-content-center
    .row
      = link_to '<button class="btn btn-primary btn-circle btn-lg"><i class="fa fa-lg fa-arrow-left" title="Kembali ke daftar status akun"></i></button>'.html_safe, status_akun_index_path, class: 'center-block'